### ISSUE TITLE
Incorrect game theme video presentation

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#11]
I am have encountered two mame game themes in which the gameplay video media is cut in size:
ES Evolution Soccer and Enigma II. I didn't go over all the mame game themes yet.

You can download the these game themes for testing here:
[test themes.zip](https://github.com/pcca-matrix/PCCA-Layout/files/4852462/test.themes.zip)

screens:
![Capture](https://user-images.githubusercontent.com/52970692/86137538-6424b780-babb-11ea-96fc-b34d0185652b.JPG)
![Capture2](https://user-images.githubusercontent.com/52970692/86137548-66871180-babb-11ea-88c4-2cc05c9bf9ef.JPG)

**Comment by pcca-matrix** [comment]
actually, I did not know that it was possible to put a video frame smaller than the video itself.
I will have to change the video shader

**Comment by Yaron2019** [comment]
Here is another interesting case because of it's unique triangular shape - it may stem from the same issue and is worth rechecking when a fix is available. The snap video is there but you can barely see it in the upper left corner of the video frame.
These are enough examples IMO, I will not post additional ones until a fix is released.

![Capture](https://user-images.githubusercontent.com/52970692/86165734-b973bf80-bae1-11ea-8f50-41c68926a987.JPG)

**Comment by Yaron2019** [comment]
This bug is now fixed. Cool!
