### ISSUE TITLE
Incorrect vertical video height?

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#12]
I am not sure if this is a theme xml issue or a bug but some game themes with vertical video frames don't present the video according to the frame size. I tried editing the theme.xml file to stretch the video but it didn't do anything, so I am suspecting a bug.

Here is one of the themes (Espgaluda II):
[espgal2.zip](https://github.com/pcca-matrix/PCCA-Layout/files/4852571/espgal2.zip)

screen:
![Capture](https://user-images.githubusercontent.com/52970692/86139414-b4047e00-babd-11ea-9d66-9c0c65175a87.JPG)

**Comment by pcca-matrix** [comment]
Yes I already noticed that 
it appears correctly stretched in hyperspin but not in hypertheme !
I must  understand how the "forceaspectratio" of hyperspin works, it's not clear

**Comment by pcca-matrix** [comment]
commenting this line do the job.

https://github.com/pcca-matrix/PCCA-Layout/blob/28556684704cf562960bddc951a0322087746663/layouts/pcca/layout.nut#L828

I remember that I did not understand how it really work , it's not clear , you can try to change in xml to "both,horizontal,vertical,none" launch  hyperspin,  it doesn't change anything !

**Comment by sergiohf** [comment]
Programming is not my thing, but in the hyperspin.nut this the video aspect works and the solution there is:

				case "forceaspect":
					if (( c.tag == "video" ) && ( v == "both" ))
						obj.preserve_aspect_ratio=false;

Hope i am not embarrasing myself, lol

**Comment by pcca-matrix** [comment]
obj.preserve_aspect_ratio  work with hyperspin "both" option.
that's not the case here.
what's the real purpose of "none, vertical,horizontal"  in a real hyperspin ?
I will look at the matter.

**Comment by pcca-matrix** [comment]
Apparently, here's how it works :

both = you can entre any width or height
none = keep width aspect ratio
horizontal = keep height aspect ratio
vertical = keep width aspect ratio

it's all the opposite of what it seems .....

I'm going to modify according to and we'll see what it looks like on the other themes.

**Comment by Yaron2019** [comment]
I commented line 828 and it seems to work

**Comment by Yaron2019** [comment]
This bug is also fixed!
