### ISSUE TITLE
Theme zorder or swf art issue?

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#14]
Randomly navigating the mame wheel I found two themes with apparent zorder issues - maybe from the theme itself using flash as artwork? Other then these all the rest looks good!

iron clad theme: 
[ironclad.zip](https://github.com/pcca-matrix/PCCA-Layout/files/4857452/ironclad.zip)

chase bombers theme:
[cbombers.zip](https://github.com/pcca-matrix/PCCA-Layout/files/4857455/cbombers.zip)

**EDIT** - After comparing both themes with my HS Unified videos the car in 'chase bombers' is located on the wrong X value and the fire in 'iron clad' is located in the wrong Y value. This is part of the bad flash implementation in AM? 

screens:
![Capture](https://user-images.githubusercontent.com/52970692/86238073-ec15ca80-bb6a-11ea-86ea-297bfed52354.JPG)
![Capture2](https://user-images.githubusercontent.com/52970692/86238078-ecae6100-bb6a-11ea-979c-a6c7d7a514ba.JPG)

**Comment by pcca-matrix** [comment]
Yes, this is one of the problems with swf ! 
hyperspin also has alignment inconsistency with swf, so it's hard to understand what's going on and recreate it.

look at the theme "dragon view" (snes) , it has false x ,y coordinates but  have a correct rendering in hyperspin.

**Comment by Yaron2019** [comment]
>  hyperspin also has alignment inconsistency with swf, so it's hard to understand what's going on and recreate it.

Interesting. So we have nothing to do with it I guess. Closing issue.
