### ISSUE TITLE
empty screen

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#17]
When you first enter the theme from the main menu, other theme or the pcca layout menu itself it doesn't load anything but the current wheel logo
![Capture](https://user-images.githubusercontent.com/52970692/90310286-28ed1500-debe-11ea-86f7-73f8ac182a62.JPG)

**Comment by pcca-matrix** [comment]
this should be fixed with the last commit !

**Comment by Yaron2019** [comment]
Resolved!
