### ISSUE TITLE
distorted elements when aspect is set to stretch

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#18]
look at the ball and the character at the bottom right when I set the aspect to stretch. You can also see the empty display bug in action.

https://youtu.be/CBz2Ztad07o

**Comment by Yaron2019** [comment]
This is the default NES HS theme - look at the snap video borders. I think it's the same issue.

![Capture](https://user-images.githubusercontent.com/52970692/90332619-5d2f0700-df8c-11ea-946c-7cd023f58dca.JPG)

**Comment by Yaron2019** [comment]
I have hyperspin now running all the same themes and I can see similar distortions in the game theme I posted at the top as a video, but the NES system theme is good. Are we looking here at the results of the bad flash implementation in AM?
If so, I will close this issue.

**Comment by pcca-matrix** [comment]
this type of distortion cannot be fixed, when we stretch a circle lengthwise it becomes oval! 
the only way would be with complex quadratic equations on animated objects.

for the NES
I don't have this problem? , in my version of the theme there is no flash media.


![screen](https://user-images.githubusercontent.com/25477623/90398365-93a67800-e099-11ea-9c61-97bf703cf9c1.jpg)

**Comment by Yaron2019** [comment]
Give me this theme!
I want to compare with what I have here because I have no flash file either.

**Comment by pcca-matrix** [comment]
[Default.zip](https://github.com/pcca-matrix/PCCA-Layout/files/5086113/Default.zip)

**Comment by Yaron2019** [comment]
Ok now it works and I see the difference. Yours on the left, mine on the right.
So this is the normal stretch effect. Closed!

![Capture](https://user-images.githubusercontent.com/52970692/90479735-23314280-e0fd-11ea-914f-a7c736980d55.JPG)
