### ISSUE TITLE
Inconsistent wheel logo pulse behaviour

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#19]
This is a newly introduced issue:

https://youtu.be/dHoRyNdQwn4

When loading the theme, the wheel logo pulse behavior depends on how quickly you navigate the wheel the first time.

**Comment by pcca-matrix** [comment]
i know , the conveyor module will be completely rewritten to fix all anims problems while wheel is spinning.

**Comment by Yaron2019** [comment]
I seems to be resolved with the latest commit. Closing this issue.
