### ISSUE TITLE
Wheel logos don't fade after navigation

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#20]
Pcca loads fine with only current wheel logo visible but after navigating the wheel the rest of the wheel logos stay visible.
(I made no changes to pcca's layout options)

Is this related to your intention to rewrite the conveyor?

**Comment by pcca-matrix** [comment]
oups I forgot to uncomment line 1037, it's because I'm doing tests to change the conveyor !

**Comment by Yaron2019** [comment]
Resolved!
