### ISSUE TITLE
Feature request: Ability to hide all game info

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#21]
When you have time, I request an ability to show/hide all game info. I can probably add this feature myself but developers usually don't like other people touching their code 

EDIT: well, tried to modify the code here on my pc but it starts breaking all the functions. Found myself changing too much things which means I don't know how to do it in an elegant manner. So I leave this to you :D

**Comment by pcca-matrix** [comment]
implemented

**Comment by Yaron2019** [comment]
Feature added! Thanks!
