### ISSUE TITLE
Displays Menu shows game counts for currently applied filters instead of all games

### ISSUE THREAD

**Issue by progets** [pcca-matrix/PCCA-Layout#22]
I'm not sure if this is by design or a bug but as the title describes, displays menu game counts are based on the last applied filter and not the total game counts for each system.

**Comment by Yaron2019** [comment]
Nice catch. It's good to see you here.

**Comment by pcca-matrix** [comment]
Very nice ! it refresh the list size when you'r on a filtered list , it's fixed thanks!

**Comment by Yaron2019** [comment]
Using the latest commit, the displays menu game count is equal to -1 after entering a system screen for the first time. The second time the you entem the system and exit, the count is correct.

https://youtu.be/NV8WOAEljWU

**Comment by progets** [comment]
Wow, that was fast! Looks good now. I think this is what most people want to see (the total counts) vs. the filter counts). Thanks and keep up the great work!
