### ISSUE TITLE
Script Error in transition function: hs_transition - the index '5' does not exist

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#23]
Value in line 1268 exceeds the array size of 5 defined in the for loop in line 337

If I change the code to: `if (sid > 4) sid = 0;`  there is no error of course but the array is too small and the sound gets cut again in fast wheel navigation.

We should increase the size of the array - my testing shows that 10 is the right size and the sound never gets cut (even the longest sounds).

For tiny stuff like this do you want me to do a commit or leave it to you?

**Comment by pcca-matrix** [comment]
better to change line 337 i<6 
more is disturbing when you have long sounds-fx like in the playstation or nintendo pack (some are 10 secs long) it gives a 
 weird cacophony.

better to leave a simple bug report for the small bugs so i fix them all in 1 single commit.

**Comment by Yaron2019** [comment]
Resolved!
