### ISSUE TITLE
x,y game info coords

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#24]
I don't think that the 'y' coordinates does anything. doesn't move whatever the value i place there.

I think it's also in an 'y,x' order and not the traditional 'x,y' order - the second value moves the game info on the x axis.

EDIT: something is very weird there, see video:
https://youtu.be/l0KHZddv7Vs

**EDIT2: I think I got the bug. line 373, wrong array cell: `I_x = g_c[1]` should be `I_x = g_c[0]`

BTW - the values '0,500' do not move the game info surface, while the values '1,500' do move it. I guess in line 375 it should be
I_x >= 0 and I_y >= 0 ? it works well when I changed the code here**

**Comment by pcca-matrix** [comment]
nice catch ! it's fixed thanks

**Comment by Yaron2019** [comment]
Resolved!
