### ISSUE TITLE
Joystick animation?

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#26]
While in Mame, Joystick animation shows only main menu joystick (the red one: Next/Previous System) and not the light blue one (Next/Previous Game) used for the systems themelves - is this by design or a bug?

**Comment by Yaron2019** [comment]
Great, the joysticks are now working properly. 
There is no "Press Start" or "Free Play" animations in the systems screen. They show on the main menu though,

**Comment by pcca-matrix** [comment]
"Press start" and "freeplay" in an hyperspin default installation is the file SpecialBx.swf , 
if your system themes does not have any specialB file , it does not display , altough if you want the specialB artwork from MainMenu you must have that in the system_name.ini

```
[Special Art B]
default=true
active=true
```
exactly as Hyperspin

**Comment by Yaron2019** [comment]
Can you please upload all your ini files that you have in the pcca/settings folder so we use the exact same data for testing?
It will make our testing more effective.

**Comment by pcca-matrix** [comment]
posting the ini will not help since I change them very often to test all the options.
it will rather be necessary that i explain each option / value in the redame !

but here is an ini with almost all the options

```

[sounds]
game_sounds=true
wheel_click=true

[themes]
animate_out_default=false
reload_backgrounds=false
bezels_on_top=false
crt_scanline=true

[pointer]
x=976
y=385
animated=true
fade=false

[wheel]
alpha=0.40
speed=high
fade_time=-1
slots=12

[Special Art A]
default=false
active=true
x=512
y=640
in=2.2
out=.5
length =  3
delay=0
type=bounce
start=bottom

[Special Art B]
default=true
active=true
x=512
y=540
in=3.2
out=1.5
length=5
delay=0
type=fade
start=none
```

**Comment by Yaron2019** [comment]
I copied what you posted and placed it in a Mame.ini file in the pcca/Settings folder.
I need to manually change the x and y params? doesn't sound right...

![Capture](https://user-images.githubusercontent.com/52970692/90396794-d7cb5580-e064-11ea-84e5-13f3f1b440e3.JPG)

**Comment by Yaron2019** [comment]
So I created a Mame.ini i the pcca/Settings folder and I had to delete the x=,y= values as it would load all the special art in the middle of the screen. So now it loads at correct place at the bottom, but the joystick is red again in the mame system screen.
If I remove the ini file the blue joystick is back but without the other special art.

Am I doing something wrong or is it a bug?

**Comment by Yaron2019** [comment]
Ok I figured everything out - disregard any other post you might have recieved on this issue.
All I needed to do was set the x and y to 0 and that's it.

Resolved!

**Comment by Yaron2019** [comment]
Ehhhem, well not closed yet. The 'press start' special art shows only once. When it disappears it doesn't get shown again in the mame system. It works as intended in the main menu.

**Comment by pcca-matrix** [comment]
you tested with the last commit?
