### ISSUE TITLE
Default Mame theme - video.png covers mame logo

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#27]
Take a look at this screenshot: the large one is AM with pcca and the small one in is Hyperspin. Both running the default mame theme. In pcca, see the Mame logo and text rendered behind the area of the snap video?
Currently it's the only theme I can reproduce it in and ONLY in the main menu. I will investigate more.

**EDIT:**
Ok, so I compared the default mame themes in the systems and main menu and the difference is that in the main menu theme there is an additional file called Video.png. It is the one rendred ontop of the Mame logo and text (Artwork1.png).
I don't know if this is a bug... you decide.

AM:
![AM](https://user-images.githubusercontent.com/52970692/90332033-610c5a80-df87-11ea-90da-de90f248ad4b.JPG)

HS:
![HS](https://user-images.githubusercontent.com/52970692/90332039-69fd2c00-df87-11ea-95fe-643dfed98dd9.JPG)

**Comment by pcca-matrix** [comment]
dont have same result here

![screen](https://user-images.githubusercontent.com/25477623/90339405-d19b9180-dff0-11ea-830a-af6bf404a888.jpg)

can yo please  delete the attract.am file and restart attract-mode.

let me know if it fix

**Comment by Yaron2019** [comment]
I just deleted my mame main menu theme and copied the default mame main menu theme from the Hyperspin install zip - meaning it is as vanilla as can be. Same result. What I do see though is that it has a file 'Background.swf' - I remember you said that these can cause issues, no?

Here is the theme:
[MAME.zip](https://github.com/pcca-matrix/PCCA-Layout/files/5082753/MAME.zip)

**Comment by pcca-matrix** [comment]
exactly, my version of the theme has the background in PNG and not in swf.

unfortunately this is one of the bug with flash media ...

**Comment by Yaron2019** [comment]
Ok. Closing this issue.
