### ISSUE TITLE
When using layout option "Aspect = Stretched" the overview surface & text is less than ideal

### ISSUE THREAD

**Issue by progets** [pcca-matrix/PCCA-Layout#30]
When using layout option "Aspect = Stretched" the overview is less than ideal. Both the surface and text do not extend across the full screen (they stop short on the left) and they also go underneath the wheel layer artwork (on the right).

I'm not looking for every issue I point out to be addressed. This is more of a post to show improvement, or at least what I perceive to be more ideal.

Thanks for the great layout.

**Comment by pcca-matrix** [comment]
Hi progets,
it's a good thing to post any bug or improvement !

what's your screen res ?
can you attach a screenshot? 
what you describe is the result of background stretch without bezel rather than full theme stretch aspect.

**Comment by progets** [comment]
resolution is 1366 x 768
Here's a link to the screenshot [https://filebin.net/bdgqu2vi7tbr6f6e](url)

**Comment by progets** [comment]
Ok, you fixed the overview layer and text. The new layout.nut now has other issues, it doesn't load anything other than the wheel when first running AM or when first entering any menu. There is no background and no video. Once the wheel is moved then things seem to working properly but the problem reappears when changing to another system or main menu (displays menu).
