### ISSUE TITLE
Game count

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#31]
Using the latest commits, I did the following test and observed the following behavior:
- I delete the pcca.stats to force pcca to recount the games for each system.
- I launch AM and pcca automatically refreshes the game count for each system but it does not show in the main menu.
- I check the newly created pcca.stats file and it does include all the relevant game counts and they are correct.
- When I enter the mame system where I have filters it changes the game count to correspond to the filters I have for it.
- When I enter a system without filters it changes the game count to -1 (-1 is also shown in pcca.stats and in the main menu) and when I re-enter the same system it changes to the correct game count.

This test video:
https://youtu.be/a3c9mwyOJpY

This is the console printout of this entire test:
[console dump.zip](https://github.com/pcca-matrix/PCCA-Layout/files/5082931/console.dump.zip)

The attract.cfg file for this test:
[attract.zip](https://github.com/pcca-matrix/PCCA-Layout/files/5082944/attract.zip)

**Comment by pcca-matrix** [comment]
can't reproduce
isn't the same when Track Usage is set to No ?
https://github.com/pcca-matrix/PCCA-Layout/issues/25

**Comment by Yaron2019** [comment]
No, this is unrelated to the latest commits. I tested it again just now. The behavior is still as I described in the first post.

**Comment by Yaron2019** [comment]
There is a clue - The last system on my list is Daphne. When I delete pcca.stats and then launch AM, pcca generates the pcca.stats file but only the daphne system shows the game count in the main menu page. The rest of the systems don't show anything. If I enter any of these systems the process happens as I described.

My hunch is that the code is accessing some wrong array cell or something like that. Why is the daphne system the only one with the game count? and it does not turn to -1 when I enter its system!

**Comment by Yaron2019** [comment]
Here is another interesting thing: the pcca.stats file contains 80 systems which is way more systems then I have in my main menu and attract.cfg! This means that the layout is reading stats that are somewhere in the attract mode setup of the user BUT NOT in his current attract.cfg file! This is an opening for exactly this kind of issue IMO.

**Comment by pcca-matrix** [comment]
Ok I understand better , it should work correctly now.

**Comment by Yaron2019** [comment]
Using the latest commits, I now have abetter view of the issue.
I deleted the pcca.stats file and launched AM. It generated a correct list of the systems with their count.
I backed up that file without closing AM and then entered three systems: SNK Neo Geo, Nintendo 64 and SNES.
Each time when I exited one of those systems back to the main menu it showed a count of -1 BUT if you look at the pcca.stats file, you will see TWO counts - one correct and one -1. The initial count uses the rom list name of the system while the second count uses the display name of the system. The display name is the one that generates the -1. 
So this tells us it generates a second count when you first enter a system instead of using the initial correct count.

Here are the files for your comparison:
[pcca stats.zip](https://github.com/pcca-matrix/PCCA-Layout/files/5088651/pcca.stats.zip)

**Comment by pcca-matrix** [comment]
That should do the trick :)
(https://github.com/pcca-matrix/PCCA-Layout/commit/b615dc9fef814a2f09770ab48c7a047c562819d9)
 let me know

**Comment by Yaron2019** [comment]
Almost there!  
All systems show the correct count and have no issue except of mame which is the only system I have filters for in thr attract.vfg file. So the initial count is correct (3653 games when pcca.stats is generated for the first time) and when I enter the mame theme and exit it the count is 2877 which is the number of games after filtering. The pcca.stats file shows two entries for mame:
[pcca.zip](https://github.com/pcca-matrix/PCCA-Layout/files/5089340/pcca.zip)


Here is my mame entry in attract,cfg:

```
display	Mame
	layout               pcca
	romlist              mame
	in_cycle             yes
	in_menu              yes
	global_filter        
		rule                 FileIsAvailable equals 1
		rule                 Category not_contains Device|Computer|Electromechanical|Casino|handheld|tabletop|gambling
		rule                 Status equals good|imperfect
		rule                 Category not_equals casino / cards|casino / reels
	filter               All
	filter               Favourites
		rule                 Favourite equals 1

```

**Comment by Yaron2019** [comment]
If you got another post regarding this issue disregard it - it was a problem in my attract.cfg.
Issue resolved!
