### ISSUE TITLE
Screen saver - start hotkey

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#33]
Start hotkey set from screensaver menu starts AND stops the screen saver when it should only start it.

**Comment by pcca-matrix** [comment]
?? There are no hotkey settings in the screensaver menu , only blank screen start and stop command.

if you mean the screensaver hotkey set in the AM control  this is how it work.

the default AM screensaver also works like this or i missed something?

**Comment by Yaron2019** [comment]
oops.
Closed.
