### ISSUE TITLE
Screen saver - Movie Collage

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#34]
Case: Screen saver Basic Movie set to No and Movie Collage to Yes.
In Main menu screen the screensaver starts with the collage, when snaps end it switched to Basic movie and when the snap ends it returns to collage. Does not happen when in any of the system screens.

EDIT: When in main menu screen, it alternates between collage and basic movies. It can run collage once or several times and then run basic for once or twice and then run collage...

**Comment by Yaron2019** [comment]
Since the last commits today I cannot reproduce this bug.
Closed.

**Comment by Yaron2019** [comment]
I know what the bug is! It alternates between Collage and RGB! not Collage and Basic.
So in order to reproduce it, set:
Basic Movie -> No
Movie Collage -> Yes
RGB Movie - Yes

**Comment by Yaron2019** [comment]
I propose to close this issue as it is easily solved through the screensaver menu by disabling RGB. In all honestly it's not such a big deal that it alternates between collage and RGB since they are both enabled - and as such the behavior is acceptable and logical. We have better things to invest time in.

If you are not already working on this please close it or ping me and I'll do it.

**Comment by pcca-matrix** [comment]
I honestly don't understand the problem , if you set only movie collage and RGB , it is normal that it alternates only between the 2 ?
or are you talking about the fact that it is not in the order collage -> RGB -> collage -> etc ...?

**Comment by Yaron2019** [comment]
If you set Basic Movie, Collage and RGB to Yes, Basic is the default and the other two don't run. But if you set Basic to No and Collage and RGB to Yes, they alternate. The fact that there is an alternation impressed me as a bug but as I mentioned above, it is an insignificant issue after you think about it and not worth an effort. As a result I am closing this issue.
