### ISSUE TITLE
Theme not updating when entering system

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#37]
The joystick is also not updating to the blue one although I have the mame.ini file in settings folder.

https://youtu.be/FENqAMH_FzM

**Comment by pcca-matrix** [comment]
swf artwork with blue stick is system SpecialA.

if you have Mame\Images\Special\SpecialAxxx.swf 
you need to disable default.

```
[Special Art A]
default=false     <- don't use default artwork from main menu
active=true
```

**Comment by Yaron2019** [comment]
I have the Mame\Images\Special\SpecialAxxx.swf file and this is my mame.ini in the pcca/settings folder:
```

[sounds]
game_sounds=true
wheel_click=true

[themes]
animate_out_default=false
reload_backgrounds=false
bezels_on_top=true
crt_scanline=false

[pointer]
x=976
y=385
animated=true
fade=false

[wheel]
alpha=0.40
speed=high
fade_time=0.5
slots=12

[Special Art A]
default=false
active=true
x=0
y=0
in=2.2
out=.5
length =  3
delay=0
type=bounce
start=bottom

[Special Art B]
default=true
active=true
x=0
y=0
in=3.2
out=1.5
length=5
delay=0
type=fade
start=none

```

**Comment by Yaron2019** [comment]
It shows the correct joystick if I change something in the theme options after I enter the system theme. For example, I change the value of wheel fade time, when I return to the mame theme it has the blue jotstick.

Maybe the code is not reading the mame.ini when you first enter it?

**Comment by Yaron2019** [comment]
Oh for christ sake it's my stupid attract.cfg file.
Issue closed!

**Comment by pcca-matrix** [comment]
tried with your ini setting i have the correct specialA displayed.
ini is reloaded at every Transition.ToNewList looking for  system_name.ini
try with attract.am deleted maybe ?

**Comment by Yaron2019** [comment]
No no it's my fault. Sorry.
Issue closed.
