### ISSUE TITLE
When entering any system menu from the displays menu the wheel only shows the current selection

### ISSUE THREAD

**Issue by progets** [pcca-matrix/PCCA-Layout#38]
When I select a system from the displays menu I enter the system and the only wheel item show is the the currently selected system. I only see one item in the wheel and not the whole wheel. Once the wheel is moved things work as expected.

This happened after changes were made in the last 24 hours.

**Comment by pcca-matrix** [comment]
this is the expected behavior
this was not the case before ??

Maybe i should improve this part with more flexible options

**Comment by Yaron2019** [comment]
To the best of my knowledge It was always the case but progets has a point as it creates an inconsistent behavior of the wheel and I think it will look better. Just my opinion.

**Comment by progets** [comment]
I guess I didn't notice this before, my mistake. In HS the entire wheel is shown and then it fades out.
