### ISSUE TITLE
Add default ini files to the Settings folder?

### ISSUE THREAD

**Issue by ghost** [pcca-matrix/PCCA-Layout#39]
I have prepared some ini files that I want to add to the pcca/settings folder but I have no "push" access.
I've copied these ini files from the HS installation zip and just set x= and y= to zero in the special art sections. It seems to work in all resolutions and aspect ratios, and do not produce errors in the console when navigating AM or launching games.

Do you want to add it to the Settings folder?

[Settings.zip](https://github.com/pcca-matrix/PCCA-Layout/files/5101600/Settings.zip)

They are all the same with the exception of Main Menu.ini. You can check them out and if there are changes to be made tell me.

**Comment by pcca-matrix** [comment]
Thanks but from version 2.50 the ini is set from the theme interface ! sorry for the late answer
