### ISSUE TITLE
AM Freeze with error: index 'KeyboardSearch' does not exist

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#42]
Downloaded the latest commits. When launching AM I get an error:

AN ERROR HAS OCCURED [the index 'KeyboardSearch' does not exist]

CALLSTACK
*FUNCTION [main()] D:\Arcade\attract\layouts/pcca/layout.nut line [1142]

Get this screen and AM freezes:
![Capture](https://user-images.githubusercontent.com/52970692/91266107-0f11c480-e73f-11ea-8f6b-d084d4d50ac5.JPG)

**Comment by pcca-matrix** [comment]
I forgot that the default installation did not have the plugin !

**Comment by Yaron2019** [comment]
Resolved
