### ISSUE TITLE
Search: wheel logo not updating 

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#44]
If you navigate to the first game on the wheel and then search for a game with a completely different name, the results don't update the first wheel logo. 
Challenge: I know from experience that this is a long standing bug in all AM search modules - including the one you used. I saw that you fixed a similar bug the same way I did with AM's default search plugin on my pc "fe.list.search_rule = "";"  but 
'Andrew-I-Move-slower-then-a-Glacier-Mickelson' never accepted my commit. Fix this remaining edge-case bug and you are KING. To motivate you even further, I will also throw in my recipe for middle eastern Lamb Kabsa so you can weep in happiness when you eat!

https://youtu.be/i2JSbM11Peo

**Comment by pcca-matrix** [comment]
Hey This is getting interesting!  ;) 

I'm going to watch but I think it's rather directly in AM  than in squirrel that it could be fixed.

**Comment by Yaron2019** [comment]
You are our last hope! :D

**Comment by pcca-matrix** [comment]
Fixed in AM/AM+
