### ISSUE TITLE
Search feature doesn't update the wheel until the wheel is moved

### ISSUE THREAD

**Issue by progets** [pcca-matrix/PCCA-Layout#45]
The search feature is a great idea, almost a must have. I love the fact that you're using the per system letters from HS for the keyboard, it's a great idea and nice touch. The issue is once you searched you only see one game on the wheel. The other search result games don't appear until the wheels is moved. The problem is the same as I mentioned here https://github.com/pcca-matrix/PCCA-Layout/issues/38 but when using the new search feature. I think this one of the biggest issues with your layout. I know you have a ton of time and effort in this but the wheel needs to be perfect for this to be a success. After all, HS was all about the wheel.

Take my opinion with a grain of salt. Thanks for the hard work.

**Comment by pcca-matrix** [comment]
yep you right , i'm going to change it to respect HS behavior.
later i rewrite totally the conveyor module with more flexible options.
