### ISSUE TITLE
Old letter shown before new one

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#48]
When navigating the wheel by using the next/previous letter, the former letter graphics is shown for a split second before the new one. Fix:
Move code from line 1549 "letters.visible = true;" to here (line 1508 in function hs_tick) :

```
    if(trigger_letter == true){
        local firstl = fe.game_info(Info.Title);
        letters.file_name = medias_path + fe.list.name + "/Images/Letters/" + firstl.slice(0,1) + ".png";
        FE_Sound_Letter_Click.playing = true;
	**letters.visible = true;**
        trigger_letter = false;
    }

```

**Comment by pcca-matrix** [comment]
Thanks for identifying the issue Yaron !

**Comment by Yaron2019** [comment]
My pleasure. Resolved!
