### ISSUE TITLE
Letter stays on screen

### ISSUE THREAD

**Issue by Yaron2019** [pcca-matrix/PCCA-Layout#49]
Press the next/previous letter hotkey and immediately and rpeatedly press the next/previous game hotkey - the letter will remain onscreen.

https://youtu.be/a38Xtc2uZ9g

**Comment by pcca-matrix** [comment]
Should be fixed with https://github.com/pcca-matrix/PCCA-Layout/commit/4dc94b76130248cfbc5d8f9765b06b5bf0bc6a5a

**Comment by Yaron2019** [comment]
Latest commits didn't resolve this issue

**Comment by pcca-matrix** [comment]
strange , i tried on 2 different configs, clean install and don't have this problem. 
Except with the small word (The , Vs. , etc) since AM  jump to the following letter after the word  
ex:"The, a, b, c, d ...."

**Comment by Yaron2019** [comment]
Test 2, same result:
https://youtu.be/6LuaFcXr0q0

**Comment by pcca-matrix** [comment]
Ok i see
this happen when you use next or prev display as well.

**Comment by Yaron2019** [comment]
Resolved
