### ISSUE TITLE
Help, backgrounds inside the zipped theme, but it doesn't load?

### ISSUE THREAD

**Issue by hedergim** [pcca-matrix/PCCA-Layout#5]
I've managed to run everything right, but the backgrounds don't appear in any theme, the backgrounds are inside the zipped theme, but it doesn't load, why? Please.

the backgrounds of the zipped themes do not appear, the themes already have the background inside the zip, but it simply does not appear on the pcca, why?

I don’t know how to use github, can I ask this question here? I’m waiting for an answer, thanks, congratulations on the project.

**Comment by pcca-matrix** [comment]
Which platform ? (Linux,Win,Mac ?) Attract-mode version ? 
is the background in the theme is correctly named "Background.png" ?
did you try to deactivate the background transition effects to see if it helps ?

Be more specific , so i can help you

**Comment by hedergim** [comment]
Attract-Mode 2.6.1 - 64-bit (Windows)

I already disabled background effect, to no avail.

the backgrounds already have the correct name background.png within the ".zip" theme
the Hyperspin themes are already inside the ".zip"

do I need to remove this background.png and put it in a folder?

in your video I see that all the backgrounds of the themes are appearing normally, mine do not appear any.

https://www.youtube.com/watch?v=tQFLZIega1M&t=3s

**Comment by pcca-matrix** [comment]
happen with all themes or just 1?

are the others artworks/videos displayed ?

could you give me the contents of the AM log

**Comment by hedergim** [comment]
remembering that my attract-v2.6.1-win64 is original, I didn't make any changes.

happen with all themes or just 1?

yes, all themes.

are the others artworks / videos displayed?

yes, everything runs perfectly.

could you give me the contents of the AM log

It is?
last_run.log ???

Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl) 
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

Config: C:\AttractMode\attract.cfg

*** Initializing display: 'corrida isometrica'
 - Loaded master romlist 'corrida isometrica' in 1 ms (25 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (50 comparisons)
Attract-Mode Version: v2.6.1
Screen aspect ratio: 
Resolution: 679x454
Shader GLSL available: 1
OS: Windows
 - Loaded layout: C:\AttractMode\layouts/Hyperspin Theme Mode/ (layout.nut)
Error opening input file: C:\AttractMode\sounds/GS2.mp3
Error loading sound file: C:\AttractMode\sounds/GS2.mp3
 - Constructed 1 filters in 0 ms (3 comparisons)
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
 - Loaded layout: C:\AttractMode\layouts/pcca/ (layout.nut)
Script Error in C:\AttractMode\modules\hs-animate\module.nut - the index 'layout' does not exist
Writing config to: C:\AttractMode\attract.cfg
Script Error in C:\AttractMode\modules\hs-animate\module.nut - the index 'layout' does not exist
Writing config to: C:\AttractMode\attract.cfg
Script Error in C:\AttractMode\modules\hs-animate\module.nut - the index 'layout' does not exist
Writing config to: C:\AttractMode\attract.cfg
 - Constructed 1 filters in 0 ms (3 comparisons)
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
 - Loaded layout: C:\AttractMode\layouts/pcca/ (layout.nut)

*** Initializing display: 'corrida'
 - Loaded master romlist 'corrida' in 0 ms (18 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (36 comparisons)
Script Error in C:\AttractMode\modules\hs-animate\module.nut - the index 'layout' does not exist
Writing config to: C:\AttractMode\attract.cfg

*** Initializing display: 'corrida'
 - Loaded master romlist 'corrida' in 0 ms (18 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (36 comparisons)
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
 - Loaded layout: C:\AttractMode\layouts/pcca/ (layout.nut)
 - Constructed 1 filters in 0 ms (3 comparisons)
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\AttractMode\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
 - Loaded layout: C:\AttractMode\layouts/pcca/ (layout.nut)

**Comment by pcca-matrix** [comment]
these lines in your log :

Error opening input file: C:\AttractMode\sounds/GS2.mp3
Loaded layout: C:\AttractMode\layouts/Hyperspin Theme Mode/

indicates that you are using another Hyperspin theme in atrract and not the pcca theme at least for your display menu !

in the readme
It is MANDATORY to set in Attract-Mode options: General->Startup Mode to 'Show Display Menu' and Displays->'Display Menu Options->'Allow Exit from 'Display Menu' to 'No'.

pcca layout MUST be set for dispay  and system menu

**Comment by hedergim** [comment]
I've already configured it the way you're talking and it still doesn't work,

I even deleted all my AttractMode and installed Zero, and it still doesn't work,

sorry to talk, but i believe you were wrong when making the pcca available to the public, you missed some typing, the pcca you have is running all the backgrounds and different from the one available for download, there was an error, sorry .

take it easy, there is an error in the download file,
congratulations on your work.

new 'last_run.log'
Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl) 
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

Config: C:\attract-v2.6.1-win64\attract.cfg

*** Initializing display: 'corrida'
 - Loaded master romlist 'corrida' in 0 ms (18 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (36 comparisons)
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
 - Loaded layout: C:\attract-v2.6.1-win64\layouts/pcca/ (layout.nut)
 - Constructed 1 filters in 0 ms (1 comparisons)
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
 - Loaded layout: C:\attract-v2.6.1-win64\layouts/pcca/ (layout.nut)

*** Initializing display: 'corrida'
 - Loaded master romlist 'corrida' in 1 ms (18 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (36 comparisons)
Script Error in C:\attract-v2.6.1-win64\modules\hs-animate\module.nut - the index 'layout' does not exist
 - Constructed 1 filters in 0 ms (1 comparisons)
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\attract-v2.6.1-win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
 - Loaded layout: C:\attract-v2.6.1-win64\layouts/pcca/ (layout.nut)

**Comment by pcca-matrix** [comment]
Ok, so the issue can be closed

**Comment by hedergim** [comment]
thanks, congratularions
