### ISSUE TITLE
the index 'game text' does not exist

### ISSUE THREAD

**Issue by muzzol** [pcca-matrix/PCCA-Layout#57]
I'm trying to install for first time and I get this error

```
Error opening input file: /home/atom/.attract/layouts/pcca/Media/Main Menu/Sound/Wheel Click.mp3
Error loading sound file: /home/atom/.attract/layouts/pcca/Media/Main Menu/Sound/Wheel Click.mp3

AN ERROR HAS OCCURED [the index 'game text' does not exist]

CALLSTACK
*FUNCTION [main()] /home/atom/.attract/layouts/pcca/layout.nut line [414]

```

this is a debian 11 fresh install with last attract from source.

it starts but I can only see a background and some info on the upper left side. here you got a screenshot: https://i.imgur.com/3Y2mmoq.png

**Comment by pcca-matrix** [comment]
I forgot some part of the futur code, it's now solved, thanks for the report
