### ISSUE TITLE
When will a new version of pcca come out? backgrounds not loaded.

### ISSUE THREAD

**Issue by hedergim** [pcca-matrix/PCCA-Layout#6]
When will a new version of pcca come out?
I want to see if the new version will be able to load the backgrounds, in your video the backgrounds appear but it doesn't actually run.

**Comment by pcca-matrix** [comment]
the current beta version loads just fine the background for all others users , you are the only one for the moment to have this problem.
 
it's on your side that it fail, do you have an existing intstalation of hyperspin with correct main menu , system theme ?

what you see on the presentation video are themes created by the users of hyperspin.fe runing on attract-mode,
 
this module allows you to use them, pcca layout does not come with any themes or backgrounds.

**Comment by hedergim** [comment]
You are saying everything I already know,

I'm a Hyperspin theme creator,

I put my Hyperspin themes to run on pcca and the backgrounds that are within the hyperspin .zip themes don't work,

you're saying what i already know.

other friends of mine are testing your project and are having the same problem.

**Comment by pcca-matrix** [comment]
can you post your attract.cfg

**Comment by hedergim** [comment]
Your pcca layout cannot run these 2 files that are within the Hyperspin .zip theme:

Background.png  and
video.png (video frame)




# Generated by Attract-Mode v2.6.1
#
display	corrida
	layout               pcca
	romlist              corrida
	in_cycle             yes
	in_menu              yes
	filter               All
	filter               Favourites
		rule                 Favourite equals 1

display	Sega 32X
	layout               Nintendo Wii
	romlist              Sega 32X
	in_cycle             yes
	in_menu              yes
	filter               All
	filter               Favourites
		rule                 Favourite equals 1

sound
	sound_volume         100
	ambient_volume       100
	movie_volume         100

input_map
	configure            Tab
	prev_letter          LControl+Up
	next_letter          LControl+Down
	filters_menu         LControl+Left
	next_filter          LControl+Right
	configure            Escape+Up
	edit_game            Escape+Down
	add_favourite        Escape+LControl
	prev_letter          Joy0 Up+Joy0 Button0
	next_letter          Joy0 Down+Joy0 Button0
	filters_menu         Joy0 Left+Joy0 Button0
	next_filter          Joy0 Right+Joy0 Button0
	configure            Joy0 Up+Joy0 Button1
	edit_game            Joy0 Down+Joy0 Button1
	add_favourite        Joy0 Button0+Joy0 Button1
	back                 Escape
	back                 Joy0 Button1
	up                   Up
	up                   Joy0 Up
	down                 Down
	down                 Joy0 Down
	left                 Left
	left                 Joy0 Left
	right                Right
	right                Joy0 Right
	select               Return
	select               LControl
	select               Joy0 Button0
	default             back	exit
	default             up	prev_game
	default             down	next_game
	default             left	prev_display
	default             right	next_display

general
	language             pt
	exit_command         
	exit_message         
	default_font         arial
	font_path            %SYSTEMROOT%/Fonts/
	screen_saver_timeout 600
	displays_menu_exit   no
	hide_brackets        no
	startup_mode         displays_menu
	confirm_favourites   yes
	confirm_exit         yes
	mouse_threshold      10
	joystick_threshold   75
	window_mode          window
	filter_wrap_mode     no_wrap
	track_usage          yes
	multiple_monitors    no
	smooth_images        yes
	selection_max_step   128
	selection_speed_ms   40
	move_mouse_on_launch yes
	scrape_snaps         yes
	scrape_marquees      yes
	scrape_flyers        yes
	scrape_wheels        yes
	scrape_fanart        no
	scrape_videos        no
	scrape_overview      yes
	thegamesdb_key       
	hide_console         no
	video_decoder        
	menu_prompt          pcca
	menu_layout          pcca

layout_config	pcca
	param                Aspect Stretch
	param                Background_Stretch Main Menu
	param                Bezels Yes
	param                Top_Bezel No
	param                animated_backgrounds Yes
	param                infos_coord 
	param                medias_path 
	param                override_transitions Yes
	param                transition_ms 300
	param                user_lang En
	param                wait_override Yes
	param                wheel_fade_time 2500
	param                wheel_type Wheel

layout_config	Atari 2600
	param                enable_bloom Yes
	param                enable_colors Yes
	param                enable_crt_scanline Medium
	param                enable_frame Yes
	param                enable_gameinfo Info and Enumerate
	param                enable_gboxart Yes
	param                enable_gcartart Yes
	param                enable_ini_anim Yes
	param                enable_pointer Yes
	param                enable_random_sound Random
	param                enable_scanline None
	param                enable_static Yes
	param                enable_wl_bg No
	param                ini_anim_trans_ms 1000
	param                mute_videos No
	param                paramxx1  
	param                paramxx2  
	param                paramxx3  
	param                paramxx4  
	param                paramxx5  
	param                set_ms_delay 1250
	param                transition_ms 200
	param                wheel_fade_ms 500
	param                wheel_fadeout Partially
	param                wheel_logo_aspect No
	param                wheel_logo_size Larger
	param                wheel_poisition Adjust Left
	param                wheel_pulse Loop
	param                wheel_semi_t No
	param                wheel_type Round
	param                wheels 10


plugin	RocketLauncher
	enabled              yes
	param                emulatorpic D:\AttractMode\media\systemlogos\
	param                fanart fanart
	param                flyer flyer
	param                marquee marquee
	param                rlpath C:\Hyperspin\RocketLauncher\RocketLauncher.exe
	param                screenshot snap
	param                video snap
	param                wheel wheel

**Comment by pcca-matrix** [comment]
video and background are 2 artworks that use the glsl shader, what is your GPU ?

otherwise if you are sure you have the right folder structure like hyperspin I don't see what it can cause the issue

**Comment by hedergim** [comment]
My GPU and integrated notebook, I have already tested it on another PC, my friends have already tested their pcca at their home on his PC, and none can load these 2 files.

The Hyperspin themes that I tested on your pcca work smoothly on my Hyperspin, and work smoothly on my friend's Hyperspin, so it's not a GPU problem.

There is a problem with the file you made available for download on GitHub,
copy a new pcca file from your PC and put it on GITHUB again so we can download it again,

this GitHub file has a problem,
create a new Upload for Us.

**Comment by pcca-matrix** [comment]
launch with attrct-console.exe and look at the cmd windows if you see some shader compil errors

**Comment by pcca-matrix** [comment]
OK ,
i tried now  on an older notebook  with Geforce 8400Gs and it fail with background and video like your issue cause of glsl shader !!

thanks to identify the issue , I will see what i can do

**Comment by hedergim** [comment]
Thank you for believing in me,

because in your youtube video it appears running the backgrouds?

There was a small mistake in the final moment that you were working on your pc.

because yours in the video already runs the background, for sure you will be able to solve this problem,

when are you going to look? I'm looking forward to using your pcca.

**Comment by pcca-matrix** [comment]
it's on the way ! stay tuned

**Comment by hedergim** [comment]
Thank you, As soon as I resolve I will tell all my friends that you have already managed to resolve.

**Comment by pcca-matrix** [comment]
it should be fixed now , let me know if you encounter any others problems on  AMD gpu.

**Comment by hedergim** [comment]
got worse,
now breaks the entire AttractMode.

you missed something.

I already reinstalled AttractMode from scratch, nothing works,

broke everything in AttractMode.

Total Crash in AttractMode, stops working.

Total Black Screen.

**Comment by pcca-matrix** [comment]
can you please send me the attract-console.exe window content

**Comment by hedergim** [comment]
The "Layout Option"
it is not accessible,
press the button but do not access.

Notebook Intel HDGraphics 4000 integrated

Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl)
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

Config: C:\AttractMode v2.6.1 win64\attract.cfg

*** Initializing display: 'corrida'
 - Loaded master romlist 'corrida' in 0 ms (18 entries kept, 0 discarded)
 - Constructed 2 filters in 0 ms (36 comparisons)
 ! Unexpectedly lost focus to: None
 ! Unexpectedly lost focus to: SearchUI.exe (7764)
Error opening input file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error loading sound file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Letter_Click.mp3
Error opening input file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error loading sound file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Click.mp3
Error opening input file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error loading sound file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_In.mp3
Error opening input file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error loading sound file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Screen_Out.mp3
Error opening input file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error loading sound file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_In.mp3
Error opening input file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error loading sound file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Out.mp3
Error opening input file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3
Error loading sound file: C:\AttractMode v2.6.1 win64\layouts/pcca/Media/Frontend/Sounds/Sound_Wheel_Jump.mp3

**Comment by hedergim** [comment]
The "Layout Option"
it is not accessible,
press the button but do not access.

Notebook Intel HDGraphics 4000 integrated

Attract-Mode v2.6.1 (Windows, SFML 2.5.1 +SWF +7z +Curl)
avcodec 58.54.100 / avformat 58.29.100 / swscale 5.5.100 / avutil 56.31.100 / swresample 3.5.100

Config: C:\AttractMode v2.6.1 win64\attract.cfg

**Comment by pcca-matrix** [comment]
don't have older hd4000 gpu on hand, but checked with intel hd4600 and it work , here is a full config working out of box on an hd4600, can you please download and test-it , this is only attract 2.6.1 with pcca layout and correct settings for 2 systems with Hyperspin theme.

i'm waiting a friend with hd4000 laptop to test on.

https://1fichier.com/?zg97pfyom2dui54jvoxx

**Comment by hedergim** [comment]
unfortunately you made your pcca Layout project worse.

before everything was working only the layouts didn't work, now everything is broken,
crashes Windows,
Total Crash,

you better go back to the previous version that only Background didn't work,

this new version is totally broken,
several friends of mine tested without success,
all Crash on Windows,
even with the file (1fishier) that you left for donload,
all my friends were sadder,
you better check the error.

**Comment by pcca-matrix** [comment]
tested on hd4000 , sorry you cannot run full (40) background transitions.

this script is not really intended to run on older GPU.

it is tested and works perfectly on:

Intel HD 4600, 530 , Radeon hd 5670, RTX 2080 Super, GTX 650, Radeon RX570
 
temporarily , if you want to run it without backgrounds, simply delete the effect.frag file in the shader folder of the pcca layout.

Video frame overlay is now displayed even with an old gpu.

when i have some free time i will make a lightened background transitions shader for the old gpu, but for the moment it is not a priority , 10 year old gpu is no longer a standard.

**Comment by hedergim** [comment]
So it is much better to leave the old version available for download, because everything was working fine, except the backgrounds,

could you leave the old version for download and create a command line in the programming to load the background from another extra folder?

even carrying a background from another folder would be interesting, as it would be completely perfect running on any GPU, since before me and my friends were running perfectly, only the background was missing,

much better the previous version than this new one, because it doesn't work.

**Comment by pcca-matrix** [comment]
simply delete the "effect.frag" file in the shader folder of the pcca layout and you disable background transitions like in the "older version"

**Comment by hedergim** [comment]
please create a schedule to run extra backgrouns directly from another folder,
I can remove all the backgrouns from the .zip and play in another folder, so you create a new version to read background from another folder, and not from within the hyerspin zip,

ready, it solves everyone's problem.

**Comment by hedergim** [comment]
[[[ simply delete the "effect.frag" file in the shader folder of the pcca layout and you disable background transitions like in the "older version" ]]]
I did it and went back to working as before,

you can create a command line to run extra backgrounds, I’m not talking about the backgrouns within the Hyperspin .zip themes,
run backgrounds from another folder, so I create a folder and place the backgrounds.

**Comment by hedergim** [comment]
If you do this to pull the backgroound from another folder, it solves everyone's problem.

**Comment by hedergim** [comment]
I'm getting a (new GPU PC) to test.

Meanwhile...

If you create an alternate version of the pcca layout for older GPUs it would be wonderful,

you would have 2 versions to download,
(old GPU pcca)
(pcca new GPU)

o (pcca GPU old) the user should create an alternate folder to place all backgrounds, (not .zip),
would be wonderful.
o (pcca GPU old) would run the background in a traditional alternative way of AttractMode, loading from an extra folder, as AttractMode already does narurally.

**Comment by pcca-matrix** [comment]
wait  some more days and i release a lightened version , so that you will have transitions even on old hardware

**Comment by pcca-matrix** [comment]
Can you please test  if it's ok with this shader ? 
Unzip effect.frag to the shader folder of pcca layout 
[effect.zip](https://github.com/pcca-matrix/PCCA-Layout/files/4740496/effect.zip)

**Comment by hedergim** [comment]
Congratulations
now everything went perfectly,
ran the perfect background,
so you can now update your GitHub,
showing that there are 2 versions, for old PC and for new PC,

I want to open another issue,
have a problem with your Wheels roulette,
exactly the wheel that is in front of the pointer has a delay, it only leaves the front when the other one arrives in place, then it gets a little ugly, can you fix it?
you will notice when you put the transition of the slower wheels, close to 400,
I'm waiting.

**Comment by pcca-matrix** [comment]
Ok , can you please close this issue and open a new one for the wheel delay, with more details on your problem , vertcial or horizontal wheel ? resolution ? Wheel transition time , Wheel fade time ?

**Comment by hedergim** [comment]
Ok
