### ISSUE TITLE
Issue on wheels and SWF font

### ISSUE THREAD

**Issue by Triplesix974** [pcca-matrix/PCCA-Layout#67]
Hi i have used Hyperspin  for years and i tried your layout for a week now and it's really good.  Nethertheless i have problems with the wheels fading option, it appears to take way more time than intended to fade. For example i want it to fade in 0.5s and it take 3-4 second to fade, i don't know if i'm doing something wrong or if it's a bug. 
Another thing i noticed is about a swf i created with a specific font that is not displayed correctly, it seems like le layout can't find the font. I installed it on my PC and put the font in the same folder as the .exe and the PCCA layout but no result. Is there a way without modifying the layout.nut to make it work? Thanks for your works.

**Comment by pcca-matrix** [comment]
Hi, 
I have added the 'fade_delay' option for the wheel ;)
https://github.com/pcca-matrix/PCCA-Layout/commit/7a070d4bdefb672a829e98c54716ab98ef2dc16f
Could you please post here the SWF file that is causing the issue, as well as the font, so i can see what's going on?

**Comment by Triplesix974** [comment]
Hi,
I'm glad you  answered my request. 
I post the 2 files here as you asked. I'll test the new option and report the results here. 
Thanks again for your time.
[pcca.zip](https://github.com/pcca-matrix/PCCA-Layout/files/14893832/pcca.zip)

**Comment by pcca-matrix** [comment]
For the SWF, this is normal, your font is not embedded in it! 
There are two solutions: either you embed it in your font with your Flash creator, or you use a Flash decompiler if it's not your creation.

https://www.free-decompiler.com/flash/issues/695-how-to-add-new-font-to-a-swf-file#:~:text=%2D%20Open%20swf%20%2D%20Right%20click%20on,new%20tag%2C%20and%20select%20Raw

But why use an SWF when the image is not animated? Instead, it would be better to use the image converted to PNG ? 
here it is .
![32x](https://github.com/pcca-matrix/PCCA-Layout/assets/25477623/e522fbe8-335e-403a-8ca5-6af17ad9a9ff)

**Comment by Triplesix974** [comment]
Thanks for your answer, i didn't know i could embed the font into the swf, i'll look into that.I use animate a lot for animated artwork but obviously ... i'm still a newbie.
The artwork is in WIP, the animated images are not in for now i just tested the date and time code, that's why it's in flash. On the other hand the font is installed on my Pc and it work out of AM but when i use it in the frontend it doesn't. 
Thank you for the solutions you suggested I'll look into that to solve the problems. I'll report back when i test the delay option.

**Comment by Triplesix974** [comment]
Ok so i tested the new option et it's perfect ;-)
another thing i just noticed is that the wheels when centered in vertical position are not correctly aligned when i use the zoom option. I suppose it's because it was meant to be use on the sides of the screen. If you have the time could you take a look idk if people use it that way, but i personaly use it on one of my machine and it's great. 
Anyway thanks for all.
I tried to understand how to make donations for you and i'm sorry i haven't understand the XMR BTC and DOGE thing if you could explain i'll be glad to help.

**Comment by pcca-matrix** [comment]
Can you be more specific about the issue you're encountering with the vertical wheel? 

i don't quite understand what you mean by 'not correctly aligned'.

you could show me what's wrong in a screenshot if it's easier for you.

The wheel is drawn on a surface, so you can enlarge and position or tilt the surface as you like.

for the XMR, BTC, DOGE, etc. donations, these are cryptocurrencies , if you're unfamiliar, i've added a 'Buy Me a Beer' link to the donation list ;)

**Comment by Triplesix974** [comment]
Hi!

"By me a beer" worked :-)

i' ve attached a screen shot with yellow pen stroke, i've tried to show the misaligned elements. The central wheel with zoom have some kind of display limit reach problem, I dont know if this "display" can be enlarge, so that the wheel zoomed can be display entirely? I'm sorry if there are things you don't completly understand my first language is french and i haven't "spoke" english in a very long time.
![Capture d’écran 2024-04-08 143824](https://github.com/pcca-matrix/PCCA-Layout/assets/165872795/42cefe93-3189-4523-bf64-43de26a17dad)

**Comment by pcca-matrix** [comment]
Thank you for the beer, cheers! :)
Ok, I see the problem you're pointing out. When the wheel is zoomed, it goes beyond the limits of the surface. 
Additionally, due to the resize, the centering is no longer correct as it retains the previous anchor. 
I'll look into fixing that promptly. 
Thank you for identifying and reporting the issue.

PS: Pas de soucis pour s'exprimer ici en français si vous avez plus facile, c'est également ma langue maternelle ;)

**Comment by pcca-matrix** [comment]
Could you test if it now works correctly? 
If not, please open another issue with the correct denomination to avoid confusion later with the different modifications
