### ISSUE TITLE
Probleme d'affichage des "wheels" lors de la modification de position vertical et probleme affichage swf "artwork" ou " Special"

### ISSUE THREAD

**Issue by Triplesix974** [pcca-matrix/PCCA-Layout#68]
Le problème des "wheels" dans mon dernier post a été résolu, mais lors de la modification de la position des "wheels" sur l'axe Y il y a un soucis d'affichage similaire, je joint une copie écran pour montrer le problème. Il est parfois utile de pouvoir réajuster les wheels par rapport aux différents artworks.
Concernant les SWF les fichier SpecialA1, B1 etc... sont censés être jouer de maniere permanente jusqu'à la validation d'une "wheels" or la le SWF n'apparait que lors que je vais sur l'option pour modifier sa position dans le menu theme settings et il ne reste que quelques seconde après avoir quitter le menu, je joint également les fichier dont je me suis servi pour le test. C'est peut être moi qui utilise mal les options a ma disposition mais sa fait deux jours et je ne comprends pas le comportement de ces fichier SWF dans le "layout".
[Special (2).zip](https://github.com/pcca-matrix/PCCA-Layout/files/14946502/Special.2.zip)
![Capture d’écran](https://github.com/pcca-matrix/PCCA-Layout/assets/165872795/3f9af019-59b5-4c1f-adc7-cc02d41145d2)

**Comment by pcca-matrix** [comment]
Pour le premier point, généralement, on augmente le nombre d'elements de 1 et on ajuste la taille de la surface pour éviter ce genre de problémes. 
Étant donné que la wheel est dessinée sur une surface, lorsque la taille ou la poistion de la surface se trouve hors des limites de la resolution c'est ce qu'il se passe.

Pourriez-vous m'envoyer votre fichier mainmenu.ini ainsi que le thèmee tel qu'il est actuellement pour que je puisse tester de mon côté ? Cela serait plus simple.

En ce qui concerne les special artworks, oui, il y a un problème que je n'ai pas encore résolu depuis que j'ai changé le mode de fade.
 
Je suis en train de corriger cette partie.

**Comment by Triplesix974** [comment]
Merci pour votre réponse. 
Pour le thème je ne sais pas si vous voulez le dossier thème de "main menu" ou un des thèmes dans ce dossier( arcade, midway, psx etc...). La taille du dossier complet est pour le moment de 150 Mo un thème doit faire a peu près 1 Mo. Comme c'est WIP il y a certainement des choses inutiles. Je ne sais pas si je suis limité en taille sur Git pour l'envoie de fichier, quelque soit la réponse ca ne me pose pas de problème de fournir les fichier.je joint déjà le fichier ini j'attends votre réponse pour les thèmes.

Merci encore

[Main Menu (2).zip](https://github.com/pcca-matrix/PCCA-Layout/files/14948379/Main.Menu.2.zip)

**Comment by pcca-matrix** [comment]
Oui, la taille est limitée sur GitHub. Vous pouvez utiliser ceci pour uploader votre archive en choisissant "envoyer en tant que lien" 
https://www.filemail.com/fr

**Comment by Triplesix974** [comment]
j'ai diminué la taille du fichier en supprimant les vidéos. voici le lien pour le téléchargement.
https://www.filemail.com/d/mhomqzrjdkewftk

**Comment by pcca-matrix** [comment]
OK, je vois le souci. 
Je vais modifier quelques points sur le positionnement des éléments de la wheel et régler le problème des special artworks
En passant, votre thème n'est pas mal du tout, il est assez original

**Comment by Triplesix974** [comment]
Lol merci je vous enverrais une vidéo quand j'aurais fini pour vous donner une idée du résultat final. Merci pour votre travail

**Comment by pcca-matrix** [comment]
Les modifications ont été apportées ! 
Voici le fichier Main Menu.ni avec la surface légèrement agrandie afin d'éviter que les éléments ne dépassent les limites. 
Tenez-moi informé du résultat
[Main Menu.zip](https://github.com/pcca-matrix/PCCA-Layout/files/14972275/Main.Menu.zip)

**Comment by Triplesix974** [comment]
Je viens de tester la solution proposé et le résultat est le même. Lorsqu'on déplace les wheels sur l'axe Y il faudrait, je pense, que la surface affiche une partie des wheels même si ces dernières sont hors écran de cette façon le déplacement vers le haut ou vers le bas serait permettrait de voir les wheels du haut ou du bas complètement. Le cadre central du background n'est pas centré sur l'écran dont il faut abaissé un peu les wheels pour sa colle correctement.


![Capture d’écran 2024-04-15 150526](https://github.com/pcca-matrix/PCCA-Layout/assets/165872795/09a3821c-e0c5-4d88-a0b2-73533a68b808)

**Comment by pcca-matrix** [comment]
Oui c'est normale , Il suffit d'élargir la surface pour qu'elle soit plus grande que la résolution de l'écran en utilisant la touche 1 du pavé numérique! Sur l'image, on voit que la taille de la surface est de 1920x1080 avec un décalage Y de 9.3. Il faut alors ajuster la taille de la surface au minimum à  1089.3 au lieu de 1080. L’élément du dessus sera alors hors champ de vision.

**Comment by Triplesix974** [comment]
ok désolé j'avais compris comment ca fonctionnait. je viens de tester c'est ok pas de soucis pour les wheels, dés que les swf marcherons comme prévu je finirais le thème. Merci encore

**Comment by pcca-matrix** [comment]
les swf sont corrigé et doivent fonctionner maintenant, si ce n'est pas le cas essayer en supprimant le fiichier ini, il sera recrée automatiquement

**Comment by Triplesix974** [comment]
OK je viens de tester les swf ils n'apparaissent pas au lancement de attractmode il faut aller dans le spécial/position et la ils apparaissent mais si on entre dans une section( arcade, ps2 etc...) lorsqu'on revient dans le main menu ils ne sont plus la. Il faut recommencer le process et repartir dans theme settings/special/position pour qu'ils soient a l'écran, ceci dit une fois qu'ils sont affichés ils ont l'air de respecter les paramètres de thème settings concernant les special artworks.

**Comment by Triplesix974** [comment]
j'avais écrasé les anciens fichier, en testant avec une nouvelle installation ca semble marcher correctement en revanche mainmenu infos n'apparait plus( gametext dans mainmenu) je ne sais pas si c'est normal.

**Comment by pcca-matrix** [comment]
Suite à la nouvelle mise à jour, les anciennes configurations de la position de lawheel et de la surface GameInfo ont été modifiées. Je pense d'ailleurs modifier cela également en ne positionnant plus les infos sur la surface de la roue, mais directement sur le layout. En attendant, si vous souhaitez réinitialiser la position de la surface GameInfo, il vous suffit de supprimer le fichier .ini ou de repositionner la surface dans la partie visible.

**Comment by Triplesix974** [comment]
j'ai supprimé le fichier mainmenu.ini mais gameinfo n'apparait toujours pas, avez vous un mainmenu.ini ou le gameinfo apparait me fournir pour tester?

**Comment by pcca-matrix** [comment]
nous parlons bien de ceci ?
![capture](https://github.com/pcca-matrix/PCCA-Layout/assets/25477623/67bac321-adb0-45d9-b70e-27d8af6582eb)
Si il n’apparaît pas après avoir supprimer le fichier ini , c'est probablement que l'option  "Global Stats" est sur No dans les les reglages layout de AM.
quoi qu'il en soit , Je vais dissocier cette partie de la wheel afin d'avoir plus de liberté quant à son positionnement. 
J'enverrai le commit d'ici la fin de journée.

**Comment by Triplesix974** [comment]
oui c'est bien de sa qu'on parle. J'ai vérifier le  " Global stats" est bien sur yes. C'est une bonne idée de dissocier le dissocier des wheels, j'attendrais le nouveau commit pour tester a nouveau. Merci

**Comment by pcca-matrix** [comment]
Ceci devrait résoudre le problème
https://github.com/pcca-matrix/PCCA-Layout/commit/5321f0aec1b63fc65dc9e3ccde1ddb8d919c2beb

**Comment by Triplesix974** [comment]
Les game infos mainmenu et scroling text fonctionnent correctement me semble t'il. Mais les special artworks .... je ne comprends pas trop ce qui se passe, il fonctionnent normalement lorsqu'on ne bouge pas les wheels mais lorsqu'on navigue ils fonctionnent de manières aléatoires. je mets en général time in, time out et delay a zéro pour que l'animation boucle sans arrêt mais sa ne fonctionne pas est ce que je m'y prend mal ? j'utilise les mêmes fichier que j'ai envoyer pour le mainmenu.

**Comment by pcca-matrix** [comment]
Pouvez-vous essayer avec ce commit 
https://github.com/pcca-matrix/PCCA-Layout/commit/9679ac2c36c10004b6c059a655ffebc687aa2143

**Comment by Triplesix974** [comment]
sa semble marcher correctement maintenant. Je dois continuer a travailler sur le thème ( artwork, animation etc...). je retesterais a chaque fois que je finirais une portion du travail restant. si je trouve d'autres bugs je les remonterais ici. 
Merci infiniment pour la création du layout et les diverses améliorations que vous avez apporté. 
A bientôt

**Comment by pcca-matrix** [comment]
Content que cela fonctionne enfin comme vous le souhaitez. 
Je me réjouis de voir le résultat final ;) 
Je ferme cette issue puisque le problème est résolu.
