### ISSUE TITLE
Wheel delayed

### ISSUE THREAD

**Issue by hedergim** [pcca-matrix/PCCA-Layout#7]
To see this problem on the wheel, change the wheel transition option to 500, the roulette wheel will rotate slowly, so you will see that the Wheel in front of the pointer is delayed when you change the wheel, the wheel is in front of the pointer, and only leaves the front when the next wheel arrives in its place, this is wrong, the correct thing is for the wheel to leave the front of the pointer and be left with nothing, until the next wheel arrives.

delay error.

if you didn’t understand wie was talking, how do I show a video here on Github?
With a video you will understand what I'm talking about.

I like to use the 500 transition wheel, slowly turning, so I saw the problem.

wait.

**Comment by hedergim** [comment]
how can I show you this problem on video?

**Comment by pcca-matrix** [comment]
do not worry i understand and see the problem, it is due to the center wheel animation.
it is not intended to be so long (500ms)
I will release a fix later

**Comment by hedergim** [comment]
OK,
thank you,
waiting.

**Comment by hedergim** [comment]
Sorry, I don't know what to do with it,
I am not a programmer,
I just see the problems,
has this new programming code already been added to the new PCCA?

**Comment by hedergim** [comment]
Mine (pcca) is version 1.02 because my GPU only accepts this old version, other than crash, remember?

I use version 1.02 and paste the file (effect.frag) in the folder and I can run the background perfectly,

how will I be able to spin the roulette slowly without the wheel delay? if my version has to be 1.02?

what should i do with this code?

**Comment by pcca-matrix** [comment]
You can download the last version , There is a low gpu option available and i optimized the shader.

It should compile on the intel HD now.

let me know if it works on your hardware

**Comment by hedergim** [comment]
Congratulations,
Perfect,
(pcca) very beautiful.
now everything is running perfect.
it is giving some errors when we change some options and we return to attractmode, but after stopping changing the options there is no more error.

If you want I can list some things for you to try to fix in your (pcca), it is already very beautiful, but you can do it only if you want, and have time to do it, it will just get a little better for perfectionist people.

1- Add an option to decrease the amount of Wheels on the roulette wheel, as it has many wheels and is on top of the others, I see that there are 12 wheels on the screen, there may be an option to decrease to 10 or 8 wheels, this can be optional .

2- There could be an option for the wheel roulette to be a little more positioned in the center of the screen, just a little, because it is very close to the right of the screen, very at the end of the right, it could be optional to be a little further away from the right, slightly away from the right.

3- "Wheel Fade Time" does not work in the (MAIN MENU) the wheels are always shown in the MAIN MENU.

ready, your PCCA would be much more perfect with these options, but you only need to do it if you have time, and have the will and taste to do it.
Maybe not much work for you.
congratulations on your work.

**Comment by pcca-matrix** [comment]
Thanks for your report for making it better.

I added the 3 points listed above, to the last version, 

Please, in the future, close an issue when resolved and open another one to request a change or report a different bug , it's easier to read for everyone.


I close this one since it is resolved
